# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

baseURL="https://www.tabletopflore.com/"

defaultContentLanguage = "en"

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/wiki/404"

# theme="blowfish"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

enableGitInfo = true

buildDrafts = false
buildFuture = false

googleAnalytics = "G-7E7DG2KSTP"


[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'hourly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
