baseURL = 'https://www.tabletopflore.com'
languageCode = 'en-us'
title = "Flore's Insignificant Thoughts"
theme = ["edits", "anubis"]
enableRobotsTXT=true
paginate = 3


disqusShortname = "tabletopflore"

[author]
name = "Flore"
email = "drmoonlington@gmail.com"

[params]
author = "Flore"
description = "Musings about Worldbuilding and TTRPGs"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "dark-without-switcher"
readMore = false

[[params.social]]
id = "github"
name = "Moonlington"
[[params.social]]
id = "twitter"
name = "FloreVEVO"
[[params.social]]
id = "twitch"
name = "Flor3tta"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/posts/"
weight = 4

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true