baseURL = 'https://www.tabletopflore.com'
enableRobotsTXT = true
languageCode = 'en-us'
paginate = 3
refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "404.md"
theme = ["edits", "anubis"]
title = "Flore's Insignificant Thoughts"

disqusShortname = "tabletopflore"

[author]
email = "drmoonlington@gmail.com"
name = "Flore"

[params]
author = "Flore"
dateFormat = "2006-01-02"
description = "Musings about Worldbuilding and TTRPGs"
paginationSinglePost = true
readMore = false
style = "dark-without-switcher"

[[params.social]]
id = "github"
name = "Moonlington"
[[params.social]]
id = "twitter"
name = "FloreVEVO"
[[params.social]]
id = "twitch"
name = "Flor3tta"

[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/posts/"
weight = 4

[[menu.main]]
identifier = "wiki"
name = "Wiki"
url = "/wiki/"
weight = 5

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true
