baseURL = "https://www.tabletopflore.com/"
languageCode = "en-us"
theme = "poison"
paginate = 10
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries

refLinksErrorLevel = "WARNING"
refLinksNotFoundURL = "/404"

# NOTE: If using Disqus as commenting engine, uncomment and configure this line
# disqusShortname = "yourDisqusShortname"

[Author]
    name = "Flore"

[params]
    brand = "Flore's Insignificant Thoughts"                      # name of your site - appears in the sidebar
    brand_image = "/img/Red Logo.png"    # path to the image shown in the sidebar
    description = "Musings about TTRPGs and Worldbuilding" # Used as default meta description if not specified in front matter
    dark_mode = true                      # optional - defaults to false
    favicon = "/android-chrome-512x512.png"             # path to favicon (defaults to favicon.png)

    front_page_content = ["posts"]

    # MENU PLACEHOLDER
    # Menu dict keys:
        # Name:         The name to display on the menu.
        # URL:          The directory relative to the content directory.
        # HasChildren:  If the directory's files should be listed.  Default is true.
        # Limit:        If the files should be listed, how many should be shown.
    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "House Rules", URL = "https://wiki.tabletopflore.com/books/campaigns-house-rules-and-rpgs", External = true, HasChildren = false},
        {Name = "Flore's Insignificant Wiki", URL = "https://wiki.tabletopflore.com/", External = true, HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent blog posts", HasChildren = true, Limit = 5},
        # {Name = "Wiki", URL = "/wiki/", Pre = "Recent wiki articles", HasChildren = true, Limit = 5}
    ]

    # Links to your socials.  Comment or delete any you don't need/use. 
    github_url = "https://github.com/Moonlington"
    # gitlab_url = "https://gitlab.com"
    # linkedin_url = "https://linkedin.com"
    twitter_url = "https://twitter.com/FloreVEVO"
    # mastodon_url = "https://mastodon.social"
    # tryhackme_url = "https://tryhackme.com"
    # discord_url = "https://discord.com"
    youtube_url = "https://youtube.com/c/FloreVEVO"
    # instagram_url = "https://instagram.com"
    # facebook_url = "https://facebook.com"
    # flickr_url = "https://flickr.com"
    # telegram_url = "https://telegram.org"
    # matrix_url = "https://matrix.org"
    # xmpp_url = "https://xmpp.org"
    # email_url = "mailto://user@domain"
    bluesky_url = "https://bsky.app/profile/florevevo.bsky.social"

    # NOTE: If you don't want to use RSS, comment or delete the following lines
    # Adds an RSS icon to the end of the socials which links to {{ .Site.BaseURL }}/index.xml
    rss_icon = true
    # Which section the RSS icon links to, defaults to all content. See https://gohugo.io/templates/rss/#section-rss
    rss_section = "posts"

    # Hex colors for your sidebar.
    sidebar_bg_color = "#202020"            # default is #202020
    sidebar_img_border_color = "#515151"    # default is #515151
    sidebar_p_color = "#909090"             # default is #909090
    sidebar_h1_color = "#FFF"               # default is #FFF
    sidebar_a_color = "#FFF"                # default is #FFF
    sidebar_socials_color = "#FFF"          # default is #FFF
    moon_sun_color = "#FFF"                 # default is #FFF
    moon_sun_background_color = "#515151"   # default is #515151

    # Hex colors for your content in light mode.
    text_color = "#222"             # default is #222
    content_bg_color = "#FAF9F6"    # default is #FAF9F6
    post_title_color = "#303030"    # default is #303030
    list_color = "#5a5a5a"          # default is #5a5a5a
    link_color = "#f42020"          # default is #268bd2
    date_color = "#515151"          # default is #515151
    table_border_color = "#E5E5E5"  # default is #E5E5E5
    table_stripe_color = "#F9F9F9"  # default is #F9F9F9

    # Hex colors for your content in dark mode
    text_color_dark = "#eee"                # default is #eee
    content_bg_color_dark = "#121212"       # default is #121212
    post_title_color_dark = "#DBE2E9"       # default is #DBE2E9
    list_color_dark = "#9d9d9d"             # default is #9d9d9d
    link_color_dark = "#f42020"             # default is #268bd2
    date_color_dark = "#9a9a9a"             # default is #9a9a9a
    table_border_color_dark = "#515151"     # default is #515151
    table_stripe_color_dark = "#202020"     # default is #202020
    code_color = "#bf616a"                  # default is #bf616a
    code_background_color = "#E5E5E5"       # default is #E5E5E5
    code_color_dark = "#ff7f7f"             # default is #ff7f7f
    code_background_color_dark = "#393D47"  # default is #393D47

    # NOTE: If using Remark42 as commenting engine, uncomment and configure these lines
    # remark42 = true
    # remark42_host = "https://yourhost.com"
    # remark42_site_id = "your_site_id"

    # NOTE: The following three params are optional and are used to create meta tags + enhance SEO.
    og_image = "/img/Red Logo.png"                       # path to social icon - front matter: image takes precedent, then og_image, then brand_url
                                          # this is also used in the schema output as well. Image is resized to max 1200x630
                                          # For this to work though og_image and brand_url must be a path inside the assets directory
                                          # e.g. /assets/images/site/og-image.png becomes images/site/og-image.png
    # publisher_icon = ""                 # path to publisher icon - defaults to favicon, used in schema

[taxonomies]
    series = 'series'
    tags = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
